name = "OITOOLS-DOCS"
uuid = ""d4157b62-ce65-4dbc-ab7a-db8f385da21b""
keywords = ["astronomy", "interferometry"]
license = "GPLv3"
desc = "Documentation for OITOOLS"
authors = ["Fabien Baron <fbaron@gsu.edu>"]
version = "0.7.0"

[deps]
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazyAlgebra = "aeaa251e-9d76-11e9-311b-83636bf44738"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OIFITS = "53eb397e-dec1-5dcf-8dc9-2db916067267"
OptimPackNextGen = "080ffe24-4a27-4ab0-ad71-7b624e73ef8d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UltraNest = "6822f173-b0be-4018-9ee2-28bf56348d09"
